version: "2"

run:
  timeout: 5m

linters:
  default: standard
  enable:
    - misspell
    - unconvert
    - unparam
    - gosec
    - prealloc

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
